### ISSUE TITLE
City does not update and creates an unexpected token ILLEGAL error

### ISSUE THREAD

**Issue by 24434everyday** [ashikahmad/prayer-time-widget#1]
Attempting to update the City:
# Example city: Chicago
# Location:(41.953256º N, -87.662904º W)
# TimeZone: -6

calcMethod  = 2
asrMethod   = 0
latitude    = 41.95
longitude   = -87.66
timezone    = -6

cityName    : “Chicago”

City still shows Dhaka.  When I save the file I get an error that says: "unexpected token ILLEGAL" but it doesn't give me any other information to find the error.  The above is all I have changed.

**Comment by ashikahmad** [comment]
When you edit in TextEdit or other editors alike, they are not much code-friendly. In that case, QUOTAION MARK ( " ) symbol converts to LEFT/RIGHT DOUBLE QUOTATION MARK ( “ / ” ) to prettify the text. May be that is your case!
Hope it helps.

**Comment by 24434everyday** [comment]
what editor would you recommend?

On Thu, Jan 8, 2015 at 12:08 PM, Ashik Uddin Ahmad <notifications@github.com

**Comment by ashikahmad** [comment]
Any CODE-editor. TextWrangler or Sublime for example.

On Friday, January 9, 2015, 24434everyday notifications@github.com wrote:

> what editor would you recommend?
> 
> On Thu, Jan 8, 2015 at 12:08 PM, Ashik Uddin Ahmad <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> 
> > wrote:
> > 
> > When you edit in TextEdit or other editors alike, they are not much
> > code-friendly. In that case, QUOTAION MARK ( " ) symbol converts to
> > LEFT/RIGHT DOUBLE QUOTATION MARK ( “ / ” ) to prettify the text. May be
> > that is your case!
> > Hope it helps.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/ashikahmad/prayer-time-widget/issues/1#issuecomment-69221753>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ashikahmad/prayer-time-widget/issues/1#issuecomment-69224068
> .

## 

-Ashik Uddin Ahmad

┌──────────────────────────⊖─⊕─⊗─┐
│ _Ashik Uddin Ahmad_               │
│ Developer [iOS & Android]              │
│ _✉_ _ashik.u.ahmad@gmail.com ashik.u.ahmad@gmail.com_       │
│ ♜ WNeeds Ltd.                  │
└────────────────────────────────╯

**Comment by 24434everyday** [comment]
This never worked by the way.
